Montag, 22. November 2021
16:41:52

Exception Type: System.IO.DirectoryNotFoundException
Message: Ein Teil des Pfades "F:\OneDrive\PythonProjects\TUWPySimultan\PySimultan\tests\readme_examples\resources\~example4_reference_list.simultan" konnte nicht gefunden werden.
Stacktrace:
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   bei SIMULTAN.Project.ProjectLoaders.ZipProjectIO.GetFilesRecursive(DirectoryInfo _dir)
   bei SIMULTAN.Project.ProjectLoaders.ZipProjectIO.CheckLockOnFiles(DirectoryInfo _dir)
   bei SIMULTAN.Project.ProjectLoaders.ZipProjectIO.Close(HierarchicalProject _project, Boolean _save_before_closing, Boolean _unloading_follows)
   bei ComponentBuilder.ViewNEW.MainWindowContent.CloseProjectVM.CloseProject()
